services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
     - POSTGRES_USER=${DB_USERNAME}
     - POSTGRES_PASSWORD=${DB_PASSWORD}
     - POSTGRES_DB=${DB_DATABASE}
    container_name: nestjs-microservices-postgres
    volumes:
     - ./pgdata:/var/lib/postgresql/data
    ports:
     - "${DB_PORT}:5432"
    networks: [nestjs-microservices-net]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  pgadmin:
    image: dpage/pgadmin4:9.6
    restart: always
    container_name: nestjs-microservices-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_HOST_PORT}:${PGADMIN_CONTAINER_PORT}"
    depends_on:
      - db
    networks: [nestjs-microservices-net]
  
  redis:
    image: redis:7-alpine
    container_name: nestjs-microservices-redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: always
    networks: [nestjs-microservices-net]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    
  zookeeper:
    image: wurstmeister/zookeeper:latest
    platform: linux/amd64
    container_name: nestjs-microservices-zookeper
    ports:
      - "2181:2181"
    networks: [nestjs-microservices-net]

  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    platform: linux/amd64
    container_name: nestjs-microservices-kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "topic-test"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks: [nestjs-microservices-net]
    
  #KAFKA MOBİL ERİYE BAĞLANINCA ÇALIŞIYOR VE BUNU ÖNCE EXPORTLAMAN LAZIM:
  #export HOST_IP=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
  #docker-compose up

networks:
  nestjs-microservices-net:
    driver: bridge