#will be deleted
### Get the list of all roles
GET http://localhost:3000/roles

### Create a new role
POST http://localhost:3000/roles/create
Content-Type: application/json

{
    "name": "user"
}

### Get the list of all users
GET http://localhost:3000/users


# ### Create a new user with the foreign key roleId
# POST http://localhost:3000/auth/register
# Content-Type: application/json

# {
#     "email": "user@test.com",
#     "password": "user",
#     "roleId": 2
# }